In [560]:
import numpy as np
import pandas as pd

In [1513]:
df = pd.read_csv("C:\\Users\\Ä°dris AydÄ±n\\Desktop\\Sleep_health_and_lifestyle_dataset (1).csv")
df

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [1514]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person ID                374 non-null    int64
 1   Gender                   374 non-null    object
 2   Age                      374 non-null    int64
 3   Occupation               374 non-null    object
 4   Sleep Duration           374 non-null    float64
 5   Quality of Sleep         374 non-null    int64
 6   Physical Activity Level  374 non-null    int64
 7   Stress Level             374 non-null    int64
 8   BMI Category             374 non-null    object
 9   Blood Pressure           374 non-null    object
 10  Heart Rate               374 non-null    int64
 11  Daily Steps              374 non-null    int64
 12  Sleep Disorder           155 non-null    object
dtypes: float64(1), int64(7), object(5)
memory usage: 38.1+ KB

In [1515]:
df.describe()

,Person ID,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps
count,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000
mean,187.500000,42.184492,7.132086,7.312834,59.171123,5.385027,70.165775,6816.844920
std,108.108742,8.673133,0.795657,1.196956,20.830804,1.774526,4.135676,1617.915679
min,1.000000,27.000000,5.800000,4.000000,30.000000,3.000000,65.000000,3000.000000
25%,94.250000,35.250000,6.400000,6.000000,45.000000,4.000000,68.000000,5600.000000
50%,187.500000,43.000000,7.200000,7.000000,60.000000,5.000000,70.000000,7000.000000
75%,280.750000,50.000000,7.800000,8.000000,75.000000,7.000000,72.000000,8000.000000
max,374.000000,59.000000,8.500000,9.000000,90.000000,8.000000,86.000000,10000.000000

In [1516]:
df.isnull().sum()

Person ID                    0
Gender                       0
Age                          0
Occupation                   0
Sleep Duration               0
Quality of Sleep             0
Physical Activity Level      0
Stress Level                 0
BMI Category                 0
Blood Pressure               0
Heart Rate                   0
Daily Steps                  0
Sleep Disorder             219
dtype: int64

In [1517]:
df = df.dropna() # NaN satÄ±rlarÄ±nÄ±n silinmesi.
df

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
5,6,Male,28,Software Engineer,5.9,4,30,8,Obese,140/90,85,3000,Insomnia
6,7,Male,29,Teacher,6.3,6,40,7,Obese,140/90,82,3500,Insomnia
16,17,Female,29,Nurse,6.5,5,40,7,Normal Weight,132/87,80,4000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [1518]:
df = df.drop(columns=['Person ID', 'Age', 'Occupation'])  # Gereksiz sÃ¼tunlarÄ±n kaldÄ±rÄ±lmasÄ±.
df

,Gender,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
3,Male,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,Male,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
5,Male,5.9,4,30,8,Obese,140/90,85,3000,Insomnia
6,Male,6.3,6,40,7,Obese,140/90,82,3500,Insomnia
16,Female,6.5,5,40,7,Normal Weight,132/87,80,4000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...
369,Female,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,Female,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,Female,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,Female,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,Female,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [1519]:
df = pd.get_dummies(df,columns = ['Gender'])  # 'Gender' sÃ¼tununun sayÄ±sal deÄŸerli 2 sÃ¼tuna ayrÄ±lmasÄ±. (One-Hot Encoding)
df['Gender_Female'] = df['Gender_Female'].astype(int)
df['Gender_Male'] = df['Gender_Male'].astype(int) # Tip dÃ¶nÃ¼ÅŸÃ¼mÃ¼.
df

,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder,Gender_Female,Gender_Male
3,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,0,1
4,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,0,1
5,5.9,4,30,8,Obese,140/90,85,3000,Insomnia,0,1
6,6.3,6,40,7,Obese,140/90,82,3500,Insomnia,0,1
16,6.5,5,40,7,Normal Weight,132/87,80,4000,Sleep Apnea,1,0
...,...,...,...,...,...,...,...,...,...,...,...
369,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,1,0
370,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,1,0
371,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,1,0
372,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,1,0
373,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,1,0